
var bd_TI = {
  nomeArea: "TI & Computação",
  idArea: "TI",
  bgColor: 'rgba(0, 75, 117, 0.7)', borderColor: '#d1c8ec', fontColor: '#f0f8fc',
  bgColorH: 'rgba(30, 105, 147, 0.7)', borderColorH: '#d1c8ec',
  cursos: [
    { id: "BCC", nome: "Ciência da Computação" },
    { id: "BSI", nome: "Sistemas de Informação" },
    { id: "TADS", nome: "Análise e\nDesenvolvimento de Sistemas" },
    { id: "TGTI", nome: "Gestão da\nTecnologia da Informação" },
    { id: "TJD", nome: "Jogos Digitais" },
    { id: "TBD", nome: "Banco de Dados" },
    { id: "TRC", nome: "Redes de Computadores" },
    { id: "TDC", nome: "Defesa Cibernética" },
    { id: "TSI", nome: "Segurança da Informação" },
    { id: "TSInt", nome: "Sistemas para Internet" },
  ],
  UCs: [
    { id: 1, nome: "Programação de Soluções Computacionais", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "TI@TGTI", "TI@TBD", "TI@TJD", "TI@TSInt", "ENG@ECOMP" ] },
    { id: 2, nome: "Modelagem de Software", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "TI@TGTI", "TI@TBD", "TI@TJD", "TI@TSInt", "ENG@ECOMP" ] },
    { id: 3, nome: "Ambientes Computacionais\ne Conectividade", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "TI@TGTI", "TI@TRC", "TI@TBD", "TI@TSI", "TI@TDC", "TI@TSInt", "ENG@ECOMP" ] },
    { id: 4, nome: "Sistemas Computacionais\ne Segurança", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "TI@TGTI", "TI@TRC", "TI@TBD", "TI@TSI", "TI@TDC", "TI@TSInt" ] },
    { id: 5, nome: "Estudos Organizacionais", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "TI@TGTI", "TI@TBD", "TI@TRC", "TI@TSI", "TI@TDC", "TI@TSInt" ] },
    { id: 6, nome: "Sistemas\nDistribuídos e Mobile", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "TI@TSInt" ] },
    { id: 7, nome: "Usabilidade,\nDesenvolvimento Web e Mobile", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "TI@TSInt" ] },
    { id: 8, nome: "Projetos e\nProcessos de TI", cursos: [ "TI@BSI", "TI@TGTI" ] },
    { id: 9, nome: "Governança e\nServiços de TI", cursos: [ "TI@BSI", "TI@TGTI", "TI@TSI" ] },
    { id: 10, nome: "Modelos, Métodos e\nTécnicas da Engenharia de Software", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS", "ENG@ECOMP" ] },
    { id: 11, nome: "Qualidade de Software", cursos: [ "TI@BCC", "TI@BSI", "TI@TADS" ] },
    { id: 12, nome: "Análise de Dados\ne Big Data", cursos: [ "TI@BCC", "TI@BSI", "TI@TBD", "CA@PP", "CA@JO", "CA@RP", "CA@PM" ] },
    { id: 13, nome: "Inteligência Artificial", cursos: [ "TI@BCC", "TI@BSI", "TI@TBD", "TI@TDC" ] },
    { id: 14, nome: "Computação Gráfica\ne Sistemas Embarcados", cursos: [ "TI@BCC", "ENG@ECOMP" ] },
    { id: 15, nome: "Linguagens Formais,\nAutômatos e Compiladores", cursos: [ "TI@BCC", "ENG@ECOMP" ] },
    { id: 16, nome: "Estruturas de Dados", cursos: [ "TI@BCC", "ENG@ECOMP" ] },
    { id: 17, nome: "Teoria da Computação\ne Análise de Algoritmos", cursos: [ "TI@BCC" ] },
    { id: 18, nome: "Arquiteturas Empresariais", cursos: [ "TI@BSI", "TI@TGTI" ] },
    { id: 19, nome: "Direito Digital", cursos: [ "TI@BSI", "TI@TGTI", "TI@TRC", "TI@TSI", "TI@TDC", "CJ@DIR" ] },
    { id: 20, nome: "Engenharia de Dados", cursos: [ "TI@TBD" ] },
    { id: 21, nome: "Administração de Dados", cursos: [ "TI@TBD" ] },
    { id: 22, nome: "Gerência e\nSegurança de Redes", cursos: [ "TI@TRC", "TI@TSI", "TI@TDC"] },
    { id: 23, nome: "Comunicação de Dados e Protocolos", cursos: [ "TI@TRC", "TI@TSI", "TI@TDC" ] },
    { id: 24, nome: "Serviços em\nRedes Locais", cursos: [ "TI@TRC", "TI@TSI", "TI@TDC" ] },
    { id: 25, nome: "Segurança da\nInformação Aplicada", cursos: [ "TI@TSI" ] },
    { id: 26, nome: "Redes Locais\ne Convergentes", cursos: [ "TI@TRC" ] },
    { id: 27, nome: "Projeto de Redes", cursos: [ "TI@TRC" ] },
    { id: 28, nome: "Análise Forense,\nMalwares, Riscos e Vulnerabilidades", cursos: [ "TI@TDC" ] },
    { id: 29, nome: "Inteligência e\nOtimização de Interfaces", cursos: [ "TI@TSInt" ] },
    { id: 30, nome: "Marketing Digital\ne Otimização em Mecanismos de Busca", cursos: [ "TI@TSInt" ] },

    //{ id: 31, nome: "Motion e interação", cursos: [ "TI@TJD" ] },
    //{ id: 32, nome: "Expressão visual", cursos: [ "TI@TJD" ] },
    { id: 33, nome: "Game Design e\nMecânicas de Jogos", cursos: [ "TI@TJD" ] },
    { id: 34, nome: "Programação de Jogos\nWeb e Mobile", cursos: [ "TI@TJD" ] },
    { id: 35, nome: "Programação de\nJogos Multiplataforma", cursos: [ "TI@TJD" ] },
    { id: 36, nome: "Computação Gráfica\ne Modelagem 3D", cursos: [ "TI@TJD" ] },

    //{ id: 37, nome: "Desenho de Som\ne Produção Sonora", cursos: [ "TI@TJD" ] },

  ]
}
