
var bd_AUD = {
  nomeArea: "Arquitetura e Urbanismo & Design",
  idArea: "AUD",
  bgColor: 'rgba(0, 191, 54, 0.7)', borderColor: '#d1c8ec', fontColor: '#f0f8fc',
  bgColorH: 'rgba(34, 221, 84, 0.7)', borderColorH: '#d1c8ec',
  cursos: [
    { id: "ARQ", nome: "Arquitetura e Urbanismo" },
    { id: "DES", nome: "Design" },
    { id: "ARV", nome: "Artes Visuais" },
    { id: "DMO", nome: "Design de Moda" },
    { id: "DINT", nome: "Design de Interiores" },
    { id: "DGR", nome: "Design Gráfico" },
    { id: "DPR", nome: "Design de Produto" },
    { id: "MOD", nome: "Moda" },
    { id: "CRES", nome: "Conservação e Restauro" },
  ],
  UCs: [
    { id: 1, nome: "Metodologia de projeto", cursos: [ "AUD@ARQ", "AUD@ARV", "AUD@DES", "AUD@MOD", "AUD@CRES", "AUD@DINT", "AUD@DPR", "AUD@DGR" ] },
    { id: 2, nome: "Expressão visual", cursos: [ "AUD@ARQ", "AUD@ARV", "AUD@DES", "AUD@MOD", "AUD@CRES", "AUD@DINT", "AUD@DPR", "AUD@DGR" ] },
    { id: 3, nome: "Meios de representação", cursos: [ "AUD@ARQ", "AUD@ARV", "AUD@DES", "AUD@CRES", "AUD@DINT", "AUD@DPR", "AUD@DGR" ] },
    { id: 4, nome: "Estudos críticos: Arte e Cultura", cursos: [ "AUD@ARQ", "AUD@ARV", "AUD@DES", "AUD@MOD", "AUD@CRES", "AUD@DINT", "AUD@DPR", "AUD@DGR" ] },
    { id: 5, nome: "Projeto de ambientes interiores", cursos: [ "AUD@ARQ", "AUD@DINT" ] },
    { id: 6, nome: "Ambiência", cursos: [ "AUD@ARQ" ] },
    { id: 7, nome: "Projeto de habitação", cursos: [ "AUD@ARQ" ] },
    { id: 8, nome: "Análise e Dimensionamento de estruturas", cursos: [ "AUD@ARQ" ] },
    { id: 9, nome: "Projeto de paisagem urbana", cursos: [ "AUD@ARQ" ] },
    { id: 10, nome: "Topografia e Geotecnia", cursos: [ "AUD@ARQ" ] },
    { id: 11, nome: "Projeto de arquitetura e urbanismo", cursos: [ "AUD@ARQ" ] },
    { id: 12, nome: "Instalações elétricas e hidrossanitárias", cursos: [ "AUD@ARQ" ] },
    { id: 13, nome: "Projeto de restauro", cursos: [ "AUD@ARQ", "AUD@CRES" ] },
    { id: 14, nome: "Cidade", cursos: [ "AUD@ARQ" ] },
    { id: 15, nome: "Planejamento urbano e regional", cursos: [ "AUD@ARQ" ] },
    { id: 16, nome: "Edificação", cursos: [ "AUD@ARQ" ] },
    { id: 17, nome: "TFG - trabalho final de graduação", cursos: [ "AUD@ARQ" ] },
    { id: 18, nome: "TGI - trabalho de graduação integral", cursos: [ "AUD@ARQ" ] },

    { id: 19, nome: "Projetos tridimensionais", cursos: [ "AUD@ARV", "AUD@DPR" ] },
    { id: 20, nome: "Produção de espaços culturais", cursos: [ "AUD@ARV" ] },
    { id: 21, nome: "Informação e projetos gráficos", cursos: [ "AUD@ARV", "AUD@DES", "AUD@DGR" ] },
    { id: 22, nome: "Gravuras", cursos: [ "AUD@ARV" ] },
    { id: 23, nome: "Técnicas e pintura", cursos: [ "AUD@ARV" ] },
    { id: 24, nome: "Materiais", cursos: [ "AUD@ARV" ] },

    { id: 25, nome: "Design industrial", cursos: [ "AUD@DES", "AUD@DPR" ] },
    { id: 26, nome: "Projeto de produto", cursos: [ "AUD@DES", "AUD@DPR" ] },
    { id: 27, nome: "Experiência do usuário", cursos: [ "AUD@DES", "CA@PM" ] },
    { id: 28, nome: "Design de Interfaces", cursos: [ "AUD@DES", "CA@PM" ] },
    { id: 29, nome: "Branding e Identidade Visual", cursos: [ "AUD@DES", "AUD@DGR" ] },
    { id: 30, nome: "Motion e interação", cursos: [ "AUD@DES", "TI@TJD", "CA@RT", "CA@PM", "CA@CA" ] },
    { id: 31, nome: "Expressão visual", cursos: [ "AUD@DES", "TI@TJD" ] },

    { id: 32, nome: "Estudo da Imagem", cursos: [ "AUD@MOD" ] },
    { id: 33, nome: "Modelagem", cursos: [ "AUD@MOD" ] },
    { id: 34, nome: "Tecnologia Têxtil", cursos: [ "AUD@MOD" ] },
    { id: 35, nome: "Costura e Habilidades manuais", cursos: [ "AUD@MOD" ] },
    { id: 36, nome: "Repertório de Estilo", cursos: [ "AUD@MOD" ] },
    { id: 37, nome: "Negócios da Moda", cursos: [ "AUD@MOD" ] },
    { id: 38, nome: "Desenvolvimento de coleção", cursos: [ "AUD@MOD" ] },

    { id: 39, nome: "Ações culturais para promoção do patrimônio", cursos: [ "AUD@CRES" ] },
    { id: 40, nome: "Procedimentos e técnicas de intervenção", cursos: [ "AUD@CRES" ] },

    { id: 41, nome: "Projeto Ambiental", cursos: [ "AUD@DINT" ] },
    { id: 42, nome: "Projeto comercial e de serviço", cursos: [ "AUD@DINT" ] },

    { id: 43, nome: "Processos gráficos", cursos: [ "AUD@DGR" ] },

  ]
}
