
var bd = {
  nomeArea: "TI & Computação",
  cursos: [
    { id: "BCC", nome: "Ciência da Computação" },
    { id: "BSI", nome: "Sistemas de Informação" },
    { id: "TADS", nome: "Análise e\nDesenvolvimento de Sistemas" },
    { id: "TGTI", nome: "Gestão da\nTecnologia da Informação" },
    { id: "TJD", nome: "Jogos Digitais" },
    { id: "TBD", nome: "Banco de Dados" },
    { id: "TRC", nome: "Redes de Computadores" },
    { id: "TDC", nome: "Defesa Cibernética" },
    { id: "TSI", nome: "Segurança da Informação" },
    { id: "TSInt", nome: "Sistemas para Internet" },
  ],
  UCs: [
    { id: 1, nome: "Programação de \nSoluções Computacionais", cursos: [ "BCC", "BSI", "TADS", "TGTI", "TBD", "TJD", "TSInt" ] },
    { id: 2, nome: "Modelagem de Software", cursos: [ "BCC", "BSI", "TADS", "TGTI", "TBD", "TJD", "TSInt" ] },
    { id: 3, nome: "Ambientes Computacionais\ne Conectividade", cursos: [ "BCC", "BSI", "TADS", "TGTI", "TRC", "TBD", "TSI", "TDC", "TSInt" ] },
    { id: 4, nome: "Sistemas Computacionais\ne Segurança", cursos: [ "BCC", "BSI", "TADS", "TGTI", "TRC", "TBD", "TSI", "TDC", "TSInt" ] },
    { id: 5, nome: "Estudos Organizacionais", cursos: [ "BCC", "BSI", "TADS", "TGTI", "TBD", "TRC", "TSI", "TDC", "TSInt" ] },
    { id: 6, nome: "Sistemas\nDistribuídos e Mobile", cursos: [ "BCC", "BSI", "TADS", "TSInt" ] },
    { id: 7, nome: "Usabilidade,\nDesenvolvimento Web e Mobile", cursos: [ "BCC", "BSI", "TADS", "TSInt" ] },
    { id: 8, nome: "Projetos e\nProcessos de TI", cursos: [ "BSI", "TGTI" ] },
    { id: 9, nome: "Governança e\nServiços de TI", cursos: [ "BSI", "TGTI", "TSI" ] },
    { id: 10, nome: "Modelos, Métodos e\nTécnicas da Engenharia de Software", cursos: [ "BCC", "BSI", "TADS" ] },
    { id: 11, nome: "Qualidade de Software", cursos: [ "BCC", "BSI", "TADS" ] },
    { id: 12, nome: "Análise de Dados\ne Big Data", cursos: [ "BCC", "BSI", "TBD" ] },
    { id: 13, nome: "Inteligência Artificial", cursos: [ "BCC", "BSI", "TBD", "TDC" ] },
    { id: 14, nome: "Computação Gráfica\ne Sistemas Embarcados", cursos: [ "BCC" ] },
    { id: 15, nome: "Linguagens Formais,\nAutômatos e Compiladores", cursos: [ "BCC" ] },
    { id: 16, nome: "Estruturas de Dados", cursos: [ "BCC" ] },
    { id: 17, nome: "Teoria da Computação\ne Análise de Algoritmos", cursos: [ "BCC" ] },
    { id: 18, nome: "Arquiteturas Empresariais", cursos: [ "BSI", "TGTI" ] },
    { id: 19, nome: "Direito Digital", cursos: [ "BSI", "TGTI", "TRC", "TSI", "TDC" ] },
    { id: 20, nome: "Engenharia de Dados", cursos: [ "TBD" ] },
    { id: 21, nome: "Administração de Dados", cursos: [ "TBD" ] },
    { id: 22, nome: "Gerência e\nSegurança de Redes", cursos: [ "TRC", "TSI", "TDC"] },
    { id: 23, nome: "Comunicação de Dados e Protocolos", cursos: [ "TRC", "TSI", "TDC" ] },
    { id: 24, nome: "Serviços em\nRedes Locais", cursos: [ "TRC", "TSI", "TDC" ] },
    { id: 25, nome: "Segurança da\nInformação Aplicada", cursos: [ "TSI" ] },
    { id: 26, nome: "Redes Locais\ne Convergentes", cursos: [ "TRC" ] },
    { id: 27, nome: "Projeto de Redes", cursos: [ "TRC" ] },
    { id: 28, nome: "Análise Forense,\nMalwares, Riscos e Vulnerabilidades", cursos: [ "TDC" ] },
    { id: 29, nome: "Inteligência e\nOtimização de Interfaces", cursos: [ "TSInt" ] },
    { id: 30, nome: "Marketing Digital\ne Otimização em Mecanismos de Busca", cursos: [ "TSInt" ] },
    { id: 31, nome: "Motion e interação", cursos: [ "TJD" ] },
    { id: 32, nome: "Expressão visual", cursos: [ "TJD" ] },
    { id: 33, nome: "Game Design e\nMecânicas de Jogos", cursos: [ "TJD" ] },
    { id: 34, nome: "Programação de Jogos\nWeb e Mobile", cursos: [ "TJD" ] },
    { id: 35, nome: "Programação de\nJogos Multiplataforma", cursos: [ "TJD" ] },
    { id: 36, nome: "Computação Gráfica\ne Modelagem 3D", cursos: [ "TJD" ] },
    { id: 37, nome: "Desenho de Som\ne Produção Sonora", cursos: [ "TJD" ] },

  ]
}
