
var bd_GN = {
  nomeArea: "Gestão e Negócios",
  idArea: "GN",
  bgColor: 'rgba(113, 60, 5, 0.7)', borderColor: '#d1c8ec', fontColor: '#f0f8fc',
  bgColorH: 'rgba(143, 90, 35, 0.7)', borderColorH: '#d1c8ec',
  cursos: [

    { id: "BADC", nome: "Administração Comex" },
    { id: "BADP", nome: "Administração Pública" },
    { id: "BADM", nome: "Administração" },
    { id: "BRI", nome: "Relações Internacionais" },
    { id: "BCC", nome: "Ciências Contábeis" },
    { id: "BCE", nome: "Ciências Econômicas" },
    { id: "BRP", nome: "Relações Públicas" },
    { id: "TCEX", nome: "CST Comércio Exterior" },
    { id: "TCOM", nome: "CST Gestão Comercial" },
    { id: "TQUA", nome: "CST Gestão da Qualidade" },
    { id: "TCOO", nome: "CST Gestão de Cooperativas" },
    { id: "TRH", nome: "CST Gestão de RH" },
    { id: "TFIN", nome: "CST Gestão Financeira" },
    { id: "TPOR", nome: "CST Gestão Portuária" },
    { id: "TLOG", nome: "CST Logística" },
    { id: "TMKT", nome: "CST Marketing" },
    { id: "TNIM", nome: "CST Negócios Imobiliários" },
    { id: "TPGE", nome: "CST Processos Gerenciais" },
    { id: "TSEC", nome: "CST Secretariado" },
    { id: "TPUB", nome: "CST Gestão Pública" },

    //{ id: "TCIN", nome: "CST Comunicação Institucional" },
    //{ id: "TPPU", nome: "CST Produção Publicitária" },
    //{ id: "TAMB", nome: "CST Gestão Ambiental" },
    //{ id: "THOS", nome: "CST Gestão Hospitalar" },
    //{ id: "TAGR", nome: "CST Gestão Agronegócio" },
    //{ id: "ENG", nome: "Engenharias TODAS" },
    //{ id: "TIC", nome: "TI & Computação TODOS" },
    //{ id: "BJO", nome: "Jornalismo" },
    //{ id: "BPP", nome: "Publicidade e Propaganda" },
    //{ id: "BTUR", nome: "Turismo" },
    //{ id: "TTUR", nome: "Gestão Turismo" },
    //{ id: "BPS", nome: "Psicologia" },

  ],
  UCs: [

    { id: 1, nome: "", cursos: [ ] },

    { id: 1, nome: "Estudos Organizacionais", cursos: [
      "CAMA@TAMB", "CAMA@TAGR", "GN@BRP", "GN@BADC", "GN@BADM", "GN@BADP", "GN@BCE", "GN@BCC", "GN@TCEX", "GN@TCOM",
      "GN@TQUA", "GN@TCOO", "GN@TRH", "GN@TFIN", "GN@TPOR", "GN@TPUB", "GN@TLOG", "GN@TMKT", "GN@TNIM", "GN@TPGE", "GN@TSEC",
      "ENG@EEL", "ENG@ECIVI", "ENG@EET", "ENG@EP", "ENG@ECA", "ENG@ECOMP", "ENG@EME", "ENG@EQU",
      "TI@BCC", "TI@BSI", "TI@TADS", "TI@TGTI", "TI@TRC", "TI@TBD", "TI@TSI", "TI@TDC", "TI@TSInt"
    ] },
    { id: 2, nome: "Tomada de Decisão", cursos: [ "CAMA@TAGR", "CAMA@TAMB", "GN@BADC", "GN@BADM", "GN@BADP", "GN@BCE", "GN@BCC", "GN@TCEX", "GN@TCOM", "GN@TQUA", "GN@TCOO", "GN@TRH", "GN@TFIN", "GN@TPOR", "GN@TPUB", "GN@TLOG", "GN@TMKT", "GN@TNIM", "GN@TPGE", "GN@TSEC" ] },
    { id: 3, nome: "Capital Humano e Aspectos Socioculturais", cursos: [ "CH@BPS", "CAMA@TAMB", "CAMA@TAGR", "GN@BADM", "GN@BADC", "GN@BADP", "GN@BCE", "GN@BCC", "GN@TCEX", "GN@TCOM", "GN@TQUA", "GN@TCOO", "GN@TRH", "GN@TFIN", "GN@TPOR", "GN@TPUB", "GN@TLOG", "GN@TMKT", "GN@TNIM", "GN@TPGE", "GN@TSEC" ] },
    { id: 4, nome: "Ética, Valores e Cultura Organizacional", cursos: [ "GN@BADM", "GN@BADC", "GN@BADP", "GN@BCC", "GN@TRH", "GN@TSEC" ] },
    { id: 5, nome: "Registros e Demonstrações Contábeis", cursos: [ "GN@BADM", "GN@BADC", "GN@BCE", "GN@BCC", "GN@TFIN", "GN@TSEC" ] },
    { id: 6, nome: "Fundamentos Econômicos", cursos: [ "GN@BADM", "GN@BADC", "GN@BADP", "GN@BCE", "GN@BCC", "GN@TCEX", "GN@TFIN", "GN@TNIM"  ] },
    { id: 7, nome: "Gestão Estratégica de Finanças", cursos: [ "CAMA@TAMB", "CAMA@TAMB", "CAMA@TAGR", "GN@BADM", "GN@BADC", "GN@BADP", "GN@BCE", "GN@BCC", "GN@TCEX", "GN@TCOM", "GN@TFIN", "GN@TNIM", "GN@TPGE", "GN@TCOO" ] },
    { id: 8, nome: "Tendências, Cenários e Estruturas Sociais", cursos: [ "GN@BADM", "GN@BADC", "GN@BADP", "GN@BCE", "GN@BCC", "GN@BRI" ] },
    { id: 9, nome: "Globalização e Estratégia", cursos: [ "GN@BADM", "GN@BADC", "GN@BADP", "GN@BCE", "GN@BCC", "GN@BRI" ] },
    { id: 10, nome: "Administração e Integração Logística", cursos: [ "CAMA@TAMB", "GN@BADM", "GN@TLOG", ] },
    { id: 11, nome: "Administração e Integração de Operações e Qualidade", cursos: [ "CAMA@TAMB", "CAMA@TAMB", "CAMA@TAGR", "GN@BADM", "GN@TQUA", "GN@TLOG", "GN@TPGE" ] },
    { id: 12, nome: "Prospecção de Mercados e de Negócios", cursos: [ "GN@BADM", "GN@BADC", "GN@BRI" ] },
    { id: 13, nome: "Composto de Marketing e Branding", cursos: [ "CA@PP", "CA@PPU", "GN@BADM", "GN@BADC", "GN@TCOM", "GN@TCOO", "GN@TMKT", "GN@TPGE", ] },
    { id: 14, nome: "Inovação, Sustentabilidade e Competitividade Empresarial", cursos: [ "GN@BADM", "GN@BADC", "GN@TQUA", "GN@TCOO", "GN@TPOR", "GN@TPGE" ] },
    { id: 15, nome: "Mercado Financeiro e Valuation", cursos: [ "GN@BADM", "GN@BADC", "GN@BCC", "GN@TFIN", ] },
    { id: 16, nome: "Direito, Política e Estado", cursos: [ "CJ@DIR", "GN@BADP" ] },
    { id: 17, nome: "Relações Jurídicas Estatais", cursos: [ "CJ@DIR", "GN@BADP", "GN@TPUB" ] },
    { id: 18, nome: "Gestão de Operações e Serviços Públicos", cursos: [ "GN@BADP", "GN@TPUB" ] },
    { id: 19, nome: "Políticas Públicas e Terceiro Setor", cursos: [ "GN@BADP", "GN@TPUB" ] },
    { id: 20, nome: "Contabilidade Pública, Socioambiental e Internacional", cursos: [ "GN@BADP", "GN@BCC", "GN@TPUB",  ] },
    { id: 21, nome: "Diversidade, Desigualdade e Desenvolvimento", cursos: [ "GN@BADP" ] },
    { id: 22, nome: "Relações de Comércio Exterior", cursos: [ "GN@BADC", "GN@TCEX" ] },
    { id: 23, nome: "Operações de Comércio Exterior", cursos: [ "GN@BADC", "GN@TCEX" ] },
    { id: 24, nome: "Economia Política e do Setor Público", cursos: [ "GN@BCE" ] },
    { id: 25, nome: "Evolução da Ciência Econômica e o Contexto Brasileiro", cursos: [ "GN@BCE", "GN@BRI" ] },
    { id: 26, nome: "Econometria e Modelagem", cursos: [ "GN@BCE" ] },
    { id: 27, nome: "Economia de Empresas", cursos: [ "GN@BCE" ] },
    { id: 28, nome: "Macroeconomia e Economia Monetária", cursos: [ "GN@BCE" ] },
    { id: 29, nome: "Desenvolvimento Sustentável e Mercado de Capitais", cursos: [ "GN@BCE" ] },
    { id: 30, nome: "Métodos e Técnicas de Pesquisa Aplicados às Ciências Sociais", cursos: [ "GN@BCE", "GN@BRI" ] },
    { id: 31, nome: "Contabilidade Societária, Tributária e de Instituições Financeiras", cursos: [ "GN@BCC", ] },
    { id: 32, nome: "Estrutura e Análise das Demonstrações Contábeis e de Custos", cursos: [ "GN@BCC" ] },
    { id: 33, nome: "Atuária, Perícia e Pareceres Contábeis", cursos: [ "GN@BCC" ] },
    { id: 34, nome: "Auditoria e Compliance", cursos: [ "GN@BCC" ] },
    { id: 35, nome: "Direito Internacional", cursos: [ "GN@BRI" ] },
    { id: 36, nome: "Contexto Histórico das Relações Internacionais", cursos: [ "GN@BRI" ] },
    { id: 37, nome: "Segurança Internacional", cursos: [ "GN@BRI" ] },
    { id: 38, nome: "Teorias das Relações Internacionais", cursos: [ "GN@BRI" ] },
    { id: 39, nome: "Instituições, Regimes e Organizações Internacionais", cursos: [ "GN@BRI" ] },
    { id: 40, nome: "Economia Política das Relações Internacionais", cursos: [ "GN@BRI" ] },
    { id: 41, nome: "Política Externa Brasileira", cursos: [ "GN@BRI" ] },
    { id: 42, nome: "Agendas, Posicionamentos e Interesses Internacionais", cursos: [ "GN@BRI" ] },
    { id: 43, nome: "Geopolítica e Política Internacional", cursos: [ "GN@BRI" ] },
    { id: 44, nome: "Gestão Comercial", cursos: [ "GN@TCOM" ] },
    { id: 45, nome: "Experiências nas Relações de Consumo", cursos: [ "GN@TCOM", "GN@TMKT" ] },
    { id: 46, nome: "Sistemas e Ferramentas da Qualidade", cursos: [ "GN@TQUA" ] },
    { id: 47, nome: "Normalização e Auditoria da Qualidade", cursos: [ "GN@TQUA" ] },
    { id: 48, nome: "Gestão das Operações Cooperativas", cursos: [ "GN@TCOO", "CAMA@TAGR",  ] },
    { id: 49, nome: "Aprendizagem e Competências Organizacionais", cursos: [ "GN@TRH" ] },
    { id: 50, nome: "Captação e Retenção de Talentos", cursos: [ "GN@TRH" ] },
    { id: 51, nome: "Avaliação e Desenvolvimento de Pessoas", cursos: [ "GN@TRH" ] },
    { id: 52, nome: "Sistema Aduaneiro e Logística Internacional", cursos: [ "GN@TPOR" ] },
    { id: 53, nome: "Estrutura e Operações de Portos", cursos: [ "GN@TPOR" ] },
    { id: 54, nome: "Cadeia Logística Portuária", cursos: [ "GN@TPOR" ] },
    { id: 55, nome: "Operações Logísticas", cursos: [ "GN@TLOG" ] },
    { id: 56, nome: "Custos Logísticos e Nível de Serviço", cursos: [ "GN@TLOG" ] },
    { id: 57, nome: "Segmentação, Posicionamento e Canais de Distribuição", cursos: [ "GN@TMKT" ] },
    { id: 58, nome: "Experiências nas Relações de Consumo", cursos: [ "GN@TMKT "] },
    { id: 59, nome: "Estratégias de Comunicação em Marketing", cursos: [ "GN@TMKT", "GN@BRP", "CA@CI" ] },
    { id: 60, nome: "Cadeia Produtiva do Mercado Imobiliário", cursos: [ "GN@TNIM" ] },
    { id: 61, nome: "Gestão de Negócios Imobiliários", cursos: [ "GN@TNIM" ] },
    { id: 62, nome: "Planejamento e Organização de Eventos", cursos: [ "TH@BTUR", "TH@TTUR", "GN@TSEC" ] },
    { id: 63, nome: "Comunicação Organizacional", cursos: [ "CA@JO", "GN@BRP", "CA@CI", "GN@TSEC" ] },


  ]
}
