
var bd_CH = {
  nomeArea: "Ciências Humanas",
  idArea: "CH",
  bgColor: 'rgba(80, 0, 71, 0.7)', borderColor: '#d1c8ec', fontColor: '#f0f8fc',
  bgColorH: 'rgba(110, 30, 101, 0.7)', borderColorH: '#d1c8ec',
  cursos: [
    { id: "PED", nome: "Pedagogia" },
    { id: "MAT", nome: "Matemática" },
    { id: "HIST", nome: "História" },
    { id: "FIL", nome: "Filosofia" },
    { id: "LET", nome: "Letras Português Inglês" },
    { id: "CBI", nome: "Ciências Biológicas" },
    { id: "EDF", nome: "Educação Física" },
  ],
  UCs: [
    { id: 1, nome: "Inclusão e LIBRAS", cursos: [ "CH@PED", "CH@MAT", "CH@HIST", "CH@FIL", "CH@LET" , "CH@CBI" , "CH@EDF" ] },
    { id: 2, nome: "Profissão Docente e Identidade Profissional", cursos: [ "CH@PED", "CH@MAT", "CH@HIST", "CH@FIL", "CH@LET" , "CH@CBI" , "CH@EDF" ] },
    { id: 3, nome: "Organização da Educação Básica ", cursos: [ "CH@PED", "CH@MAT", "CH@HIST", "CH@FIL", "CH@LET" , "CH@CBI" , "CH@EDF" ] },
    { id: 4, nome: "Psicologia e Educação ", cursos: [ "CH@PED", "CH@MAT", "CH@HIST", "CH@FIL", "CH@LET" , "CH@CBI" , "CH@EDF" ] },
    { id: 5, nome: "Gestão Educacional", cursos: [ "CH@PED", "CH@MAT", "CH@HIST", "CH@FIL", "CH@LET" , "CH@CBI" , "CH@EDF" ] },
    { id: 6, nome: "Core Curriculum", cursos: [ "CH@PED", "CH@MAT", "CH@HIST", "CH@FIL", "CH@LET" , "CH@CBI" , "CH@EDF" ] },
    { id: 7, nome: "Globalização e Contemporaneidade ", cursos: [ "CH@PED", "CH@HIST", "CH@FIL" ] },
    { id: 8, nome: "Teorias das Ciências Humanas", cursos: [ "CH@HIST", "CH@FIL" ] },
    { id: 9, nome: "Ciências Humanas e suas Tecnologias", cursos: [ "CH@PED", "CH@HIST", "CH@FIL" ] },
    { id: 10, nome: "Ação e Poder: Ética e Filosofia Política ", cursos: [  "CH@FIL" ] },
    { id: 11, nome: "Humanismo e Anti-humanismo", cursos: [ "CH@FIL" ] },
    { id: 12, nome: "Lógica, Linguagem e Verdade", cursos: [ "CH@FIL" ] },
    { id: 13, nome: "Metafísica e Ontologia: dos Gregos aos Medievais", cursos: [ "CH@FIL" ] },
    { id: 14, nome: "Subjetividade e modernidade", cursos: [ "CH@FIL" ] },
    { id: 15, nome: "Sociedade Mercantil Europeia e América Pós-Colombiana ", cursos: [ "CH@HIST" ] },
    { id: 16, nome: "Civilizações Orientais e Civilização Greco-Romana: Política e Economia ", cursos: [ "CH@HIST" ] },
    { id: 17, nome: "Sociedade, Religião e Poder: Europa Feudal e Sociedade Ameríndia", cursos: [ "CH@HIST" ] },
    { id: 18, nome: "Relações Transatlânticas entre Brasil Escravista e África: Economia, Política e Cultura", cursos: [ "CH@HIST" ] },
    { id: 19, nome: "Formação do Brasil Contemporâneo e Direitos Humanos ", cursos: [ "CH@HIST" ] },
    { id: 20, nome: "Língua, Forma, Relação e Sentido", cursos: [ "CH@LET" ] },
    { id: 21, nome: "Interação Social e Discurso Oral", cursos: [ "CH@LET" ] },
    { id: 22, nome: "Literatura e Construção de Identidade", cursos: [ "CH@LET" ] },
    { id: 23, nome: "Gêneros Textuais", cursos: [ "CH@LET" ] },
    { id: 24, nome: "O Discurso e seus Significados", cursos: [ "CH@LET" ] },
    { id: 25, nome: "Literatura e Ação Social", cursos: [ "CH@LET" ] },
    { id: 26, nome: "O Texto e seus Paradigmas", cursos: [ "CH@LET" ] },
    { id: 27, nome: "Alfabetização e Letramento ", cursos: [ "CH@PED", "CH@LET" ] },
    { id: 28, nome: "Ferramentas paraa Matemática Aplicada", cursos: [ "CH@MAT" ] },
    { id: 29, nome: "Fenômenos Elétricos, Magneticos e Óticos", cursos: [ "CH@MAT" ] },
    { id: 30, nome: "Análise de FenômenosFísicos da Natureza", cursos: [ "CH@MAT" ] },
    { id: 31, nome: "Educação Matemática: a construção do saber e do fazer matemático ", cursos: [ "CH@PED", "CH@MAT" ] },
    { id: 32, nome: "Espaço Forma e Argumentação", cursos: [ "CH@MAT" ] },
    { id: 33, nome: "Estruturas Matemáticas ", cursos: [ "CH@MAT" ] },
    { id: 34, nome: "Representações no Espaço", cursos: [ "CH@MAT" ] },
    { id: 35, nome: "História dos Processos Numéricos e Algébricos", cursos: [ "CH@MAT" ] },
    { id: 36, nome: "Saberes Necessários à Docência em Educação Infantil ", cursos: [ "CH@PED" ] },
    { id: 37, nome: "Saberes Necessários à Docência no EnsinoFundamental Anos Iniciais  ", cursos: [ "CH@PED" ] },
    { id: 38, nome: "Ciências Naturais e suas Tecnologias ", cursos: [ "CH@PED" ,"CH@CBI" ] },
    { id: 39, nome: "Língua Portuguesa e Literatura Infantojuvenil ", cursos: [ "CH@PED" ] },
    { id: 40, nome: "Educação Física, Arte, Corpo e Movimento", cursos: [ "CH@PED" , "CH@EDF"] },
  ]
}
